### PR TITLE
allow custom source-url

### PR DESCRIPTION
**Pull request by kubicgruenfeld**
we need the source url to be customizable in our infrastructure.

this PR should not change anything on the default behaviour.

### CODE REVIEW

**Review by pracucci — APPROVED** [review]
LGTM. @genebean what's your take?

**Review by genebean — APPROVED** [review]
Makes good sense to me! Thanks for the contribution!

**Comment by genebean** [comment]
@pracucci - you wanna kick off a release to the Puppet Forge that includes this?

**Comment by pracucci** [comment]
> @pracucci - you wanna kick off a release to the Puppet Forge that includes this?

I reached out @kubicgruenfeld privately and mentioned they would like to also default promtail to 2.0.0. I think makes sense. I would suggest to wait for that PR before cutting a new release.

**Pull request merged**
